## CODE INFORMATION:

This code, with the Delay per 10K Mile metrics from July 2021 through June 2022, with create a list of Amtrak services ordered by delay per mile. In addition, below the list you can input a service to directly view its official delay per miles statistic.

# Import Packages

In [1]:
import pandas as pd
# DELAY CODES FOUND HERE: https://www.amtrak.com/content/dam/projects/dotcom/english/public/documents/corporate/HostRailroadReports/July-2021-Amtrak-Host-Railroad-Report.pdf
# METRIC REPORTS FOUND HERE: https://railroads.dot.gov/rail-network-development/passenger-rail/amtrak/intercity-passenger-rail-service-quality-and

# Import Data and (TBD) Combine It

In [2]:
data1 = pd.read_excel("DelayMetrics/FY21_Q4_Delays_Per_10K_TM_Metric.xlsx")
data2 = pd.read_excel("DelayMetrics/FY22_Q1_Delays_Per_10K_TM_Metric.xlsx")
data3 = pd.read_excel("DelayMetrics/FY22_Q2_Delays_Per_10K_TM_Metric.xlsx")
data4 = pd.read_excel("DelayMetrics/FY22_Q3_Delays_Per_10K_TM_Metric.xlsx")

data = pd.concat([data1, data2, data3, data4], axis=0)

# Get names of columns so we have them

In [3]:
print(data.columns)

Index(['Unnamed: 0', 'Fiscal Year', 'Fiscal Quarter', 'Business Line Name',
       'Service Name', 'Sub Service Name', 'Host Railroad Name',
       'Host Railroad Code', 'Delay Responsibility', 'Delay Minutes',
       'Train Miles', 'Delay per 10k Train Miles'],
      dtype='object')

# Order the Services by Official Delay per Mile

In [4]:
data_mod = data.copy()
data_mod = data_mod.groupby(['Service Name'], as_index=False).sum(numeric_only = True)
data_mod['DelayPerMile'] = data_mod['Delay Minutes'] / data_mod['Train Miles']
data_mod = data_mod[['Service Name', 'Delay Minutes', 'Train Miles', 'DelayPerMile']]
data_mod = data_mod.sort_values(by=['DelayPerMile'], ascending = True)
data_mod

           Service Name  Delay Minutes  Train Miles  DelayPerMile
17             Keystone          28662    2084937.4      0.013747
0         Acela Express          93098    4237511.6      0.021970
22   Northeast Regional         344776    9269748.8      0.037194
12               Empire         158256    3337606.4      0.047416
15             Hiawatha          38964     810443.2      0.048077
3      Capitol Corridor          89294    1824185.2      0.048950
26             Piedmont          38781     741251.0      0.052318
24             Palmetto          63586    1154647.8      0.055070
33            Vermonter          46399     832289.2      0.055749
6            Carolinian          56955    1013660.6      0.056187
11           Downeaster          58559    1020908.6      0.057360
25        Pennsylvanian          37916     640900.0      0.059161
28        Silver Meteor          66207    1103500.4      0.059997
16             Illinois         190453    2955062.0      0.064450
13       Empire Builder         213241    3277744.0      0.065057
30      Southwest Chief         196082    2982582.2      0.065742
8   City Of New Orleans          75733    1145069.0      0.066138
27         San Joaquins         176796    2634243.4      0.067115
29          Silver Star         154153    2186601.2      0.070499
5              Cardinal          50755     700342.2      0.072472
23    Pacific Surfliner         208987    2561142.0      0.081599
21             Missouri          44139     537137.0      0.082175
2     California Zephyr         268537    3224939.8      0.083269
20             Michigan         175410    1938202.8      0.090501
7              Cascades         102800    1131908.8      0.090820
18       Lake Shore Ltd         137508    1513592.8      0.090849
10             Crescent         158501    1691680.0      0.093694
9       Coast Starlight         164524    1754900.6      0.093751
14      Heartland Flyer          28556     297406.8      0.096017
1            Auto Train         128241    1232375.2      0.104060
32          Texas Eagle         194168    1791838.2      0.108362
19   Lincoln / Missouri           9754      86586.4      0.112650
4           Capitol Ltd         120981    1073830.4      0.112663
31           Sunset Ltd         155512    1199037.6      0.129697

# Get the Delay Stats for a Given Service

In [5]:
wanted = "Sunset Ltd"
data_mod[data_mod['Service Name'] == wanted]

   Service Name  Delay Minutes  Train Miles  DelayPerMile
31   Sunset Ltd         155512    1199037.6      0.129697